services:
  backend:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - database
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_URL=${REDIS_URL}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASS=${DB_PASS}
      - DB_USERNAME=${DB_USERNAME}
      - FRONTEND_URL=${FRONTEND_URL}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}

    networks:
      - newnetwork

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - newnetwork

  database:
    image: postgres:16
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test_db
    networks:
      - newnetwork

networks:
  newnetwork:
    external: true